image: python

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  tags:
    - python
  script:
    - echo 'Building...'
  only:
    refs:
      - master
  when: manual

test_job:
  stage: test
  script:
    - echo 'Testing...'
  dependencies:
    - build_job
  only:
    refs:
      - master
  tags:
    - test

deploy_job:
  stage: deploy
  script:
    - echo 'Deploying...'
  dependencies:
    - test_job
  only:
    refs:
      - master
  when: on_success
  environment:
    name: production
  tags:
    - deploy
